apiVersion: v1
kind: Service
metadata:
  labels:
    app: chascale-server
  name: chascale-server
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    nodePort: 31234
  selector:
    app: chascale-server
